# Generated by Django 5.1.6 on 2025-02-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_healthrecord_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-date']},
        ),
    ]
